# -*- coding: utf-8 -*-
"""MainProgram.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yQah4yhnMf4u2FZDVCGytUzT_fDfuWoe
"""

import mediapipe as mp
import cv2
import pandas as pd
import pickle
import numpy as np
import csv
import seaborn as sns
import matplotlib.pyplot as plt
import mediapipe as mp
import cv2
import pandas as pd
import pickle
import numpy as np
import csv
import seaborn as sns
import joblib
import os

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.calibration import CalibratedClassifierCV
from sklearn.linear_model import LogisticRegression, SGDClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import LabelEncoder

import matplotlib.pyplot as plt
from sklearn.metrics import precision_score, accuracy_score, f1_score, recall_score, confusion_matrix, roc_curve, auc
from sklearn.metrics import precision_score, accuracy_score, f1_score, recall_score, confusion_matrix, roc_curve, auc

#Intialize the Mediapipe libraries
mp_drawing = mp.solutions.drawing_utils
mp_pose = mp.solutions.pose


def calculate_angle(a,b,c):
    a = np.array(a) # First
    b = np.array(b) # Mid
    c = np.array(c) # End

    radians = np.arctan2(c[1]-b[1], c[0]-b[0]) - np.arctan2(a[1]-b[1], a[0]-b[0])
    angle = np.abs(radians*180.0/np.pi)

    if angle >180.0:
        angle = 360-angle

    return angle

def export_landmark_to_csv(csv_doc: str, buffered_data) -> None:
    try:
        IMPORTANT_LMS = [
        "NOSE",
        "LEFT_SHOULDER",
        "LEFT_HIP",
        "LEFT_KNEE",
        "LEFT_ANKLE",
        "LEFT_FOOT_INDEX"
            ]

    # Generate all columns of the data frame

        landmarks = ["Position", "Hip_Knee-Ankle_angle", "Shoulder_hip_knee_angle", "Knee_ankle_foot_angle"] # Label column

        for lm in IMPORTANT_LMS:
          landmarks += [f"{lm.lower()}_x", f"{lm.lower()}_y", f"{lm.lower()}_z", f"{lm.lower()}_v"]
        # Write all the columns to a file
        with open(csv_doc, mode="w", newline="") as f:
            csv_writer = csv.writer(f, delimiter=",", quotechar='"', quoting=csv.QUOTE_MINIMAL)
            csv_writer.writerow(landmarks)
            for data_point in buffered_data:
                results, position, angle, angle2, angle3 = data_point
                landmarks = results.pose_landmarks.landmark
                keypoints = []

                # Extract coordinate of important landmarks
                for lm in IMPORTANT_LMS:
                    keypoint = landmarks[mp_pose.PoseLandmark[lm].value]
                    keypoints.append([keypoint.x, keypoint.y, keypoint.z, keypoint.visibility])

                keypoints = list(np.array(keypoints).flatten())

                # Insert action as the label (first column)
                keypoints.insert(0, position)
                keypoints.insert(1, angle)
                keypoints.insert(2, angle2)
                keypoints.insert(3, angle3)

                # Write the row to the CSV file
                csv_writer.writerow(keypoints)

    except Exception as e:
        print(e)

def preprocess_data(csv_doc):
    # Load the data from the CSV file
    data = pd.read_csv(csv_doc)

    # Label encode the labels
    label_encoder = LabelEncoder()
    data['Position'] = label_encoder.fit_transform(data['Position'])
    print("Processing this rep")
    return data

def predict_rep(data):
    # Replace this with your actual machine learning model prediction code
    predicted_labels = loaded_model.predict(data)
    print("Predicting this rep")
    print(predicted_labels)
    return predicted_labels

def identify_most_common_label(predictions):
    # Count the occurrences of each label
    label_counts = pd.Series(predictions).value_counts()

    # Get the most common label
    most_common_label = label_counts.idxmax()

    test = {0: 'Correct Pose',
    1: 'Low Back',
    2: 'Knee too forward',
    3: 'Early Stopping'}
    print(test[most_common_label])
    return test[most_common_label]

